
{{- if .Values.metallb.enabled -}}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-addres-pool
  labels:
    {{- include "k8s-dependencies.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
spec:
  addresses:
  {{- toYaml .Values.ipPool | nindent 4 }}
---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ include "k8s-dependencies.fullname" . }}-adverticement
  labels:
    {{- include "k8s-dependencies.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "3"
spec:
  ipAddressPools:
  - ip-addres-pool
{{- end }}