{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-dependencies.serviceAccountName" . }}
  labels:
    {{- include "k8s-dependencies.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-dependencies.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: guest-user
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-dependencies.labels" . | nindent 4 }}