createClusterIssuer: true
tls:
  key: test
  crt: test
kubernetes-dashboard:
  enabled: true
  nginx-ingress:
    enabled: false
  cert-manager:
    enabled: false
  app:
    ingress:
      ingressClassName: pubing
      issuer: selfsigned
      enabled: true
      hosts:
        - k8s-db.acix.amprajin.in
      annotations:
        ingress.kubernetes.io/ssl-redirect: 'true'
        ingress.kubernetes.io/proxy-body-size: '0'
        nginx.ingress.kubernetes.io/ssl-redirect: 'true'
        nginx.ingress.kubernetes.io/proxy-body-size: '0'
        cert-manager.io/cluster-issuer: cluster-issuer-public
        konghq.com/protocols: https
        konghq.com/https-redirect-status-code: '308'
        konghq.com/write-timeout: '120000'
        konghq.com/read-timeout: '120000'
        konghq.com/connect-timeout: '120000'
kong:
  enabled: true
  replicaCount: 1
  database: "off"
  postgresql:
    enabled: false
  kong:
    extraEnvVars:
      - name: KONG_NGINX_WORKER_PROCESSES
        value: "10"
      - name: KONG_PORT_MAPS
        value: "80:8000, 443:8443"
      - name: KONG_NGINX_PROXY_PROXY_BUFFER_SIZE
        value: 160k
      - name: KONG_NGINX_PROXY_PROXY_BUFFERS
        value: 64 160k
  service:
    type: LoadBalancer
    loadBalancerIP: 172.24.10.100
    annotations:
      metallb.universe.tf/address-pool: ip-addres-pool
  proxy:
    nameOverride: kong-gateway-proxy
  deployment:
    kong:
      enabled: true
  admin:
    enabled: false
    type: LoadBalancer
    clusterIP: None
  ingressController:
    enabled: true
    ingressClass: pubing
    livenessProbe: 
      enabled: false
    readinessProbe:
      enabled: false
kong-internal:
  enabled: false
  replicaCount: 1
  database: "off"
  postgresql:
    enabled: false
  kong:
    extraEnvVars:
      - name: KONG_NGINX_WORKER_PROCESSES
        value: "5"
      - name: KONG_PORT_MAPS
        value: "80:8000, 443:8443"
      - name: KONG_NGINX_PROXY_PROXY_BUFFER_SIZE
        value: 160k
      - name: KONG_NGINX_PROXY_PROXY_BUFFERS
        value: 64 160k
  service:
    type: LoadBalancer
    loadBalancerIP: 172.24.10.101
    annotations:
      metallb.universe.tf/address-pool: ip-addres-pool
  proxy:
    nameOverride: kong-gateway-proxy
  deployment:
    kong:
      enabled: true
  admin:
    enabled: false
    type: LoadBalancer
    clusterIP: None
  ingressController:
    enabled: true
    ingressClass: pvting
    livenessProbe: 
      enabled: false
    readinessProbe:
      enabled: false
# incomplete configuration
nginx-ingress-controller:
  enabled: false
  ingressClassResource:
    name: pubing
nginx-ingress-controller-internal:
  enabled: false
  ingressClassResource:
    name: pvting

harbor:
  enabled: false
  core:
    secretKey: "oLoTiLTIVerySiLI"
    secret: "cKETERSEIaTErTHR"
    csrfKey: "rIneoPsiSeaKInEo"
  registry:
    ## @param registry.secret Secret is used to secure the upload state from client and registry storage backend. See: <https://github.com/docker/distribution/blob/master/docs/configuration.md>
    ## and registry storage backend.
    ## See: https://github.com/docker/distribution/blob/master/docs/configuration.md#http
    ## If a secret key is not specified, Helm will generate one.
    ## Must be a string of 16 chars.
    ##
    secret: "uIeTAUrItkeSpiSI"
  jobservice:
    secret: "EwCarsEaRipuscHA"
  ingress:
    core:
      hostname: core.harbor.domain
      ingressClassName: pubing
      annotations:
        ingress.kubernetes.io/ssl-redirect: 'true'
        ingress.kubernetes.io/proxy-body-size: '0'
        nginx.ingress.kubernetes.io/ssl-redirect: 'true'
        nginx.ingress.kubernetes.io/proxy-body-size: '0'
        cert-manager.io/cluster-issuer: cluster-issuer-public
        konghq.com/strip-path: 'true'
        konghq.com/protocols: https
        konghq.com/https-redirect-status-code: '308'
        konghq.com/write-timeout: '120000'
        konghq.com/read-timeout: '120000'
        konghq.com/connect-timeout: '120000'   